# Generated by Django 2.2 on 2019-08-06 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuesta', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Alumno')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('padrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Afinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afinidad', models.FloatField(default=0)),
                ('mechon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechon_set', to='usuarios.Alumno')),
                ('padrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padrino_set', to='usuarios.Alumno')),
            ],
        ),
    ]
