# Generated by Django 2.2.4 on 2019-08-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='ahijado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ahijado_asig', to='usuarios.Alumno'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='anno',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='padrino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padrino_asig', to='usuarios.Alumno'),
        ),
    ]
