# Generated by Django 2.2.4 on 2019-08-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_respuesta_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='alternativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_respuesta', to='encuesta.Alternativa'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_respuesta', to='encuesta.Encuesta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_respuesta', to='encuesta.Pregunta'),
        ),
    ]
