# Generated by Django 2.2.4 on 2019-08-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_auto_20190829_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='created_at',
        ),
    ]
