# Generated by Django 2.2.4 on 2019-08-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(choices=[('INF', 'Ejecución'), ('ICI', 'Civil')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='es_Mechon',
            field=models.BooleanField(default=True),
        ),
    ]
