# Generated by Django 2.2.4 on 2019-08-29 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190828_1641'),
        ('usuarios', '0002_auto_20190828_1649'),
    ]

    operations = [
    ]
