# Generated by Django 2.2 on 2019-06-27 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipoObligatoria', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='resultado',
            name='encuesta',
            field=models.ForeignKey(default=2018, on_delete=django.db.models.deletion.CASCADE, to='main.Encuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='fecha_realizacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Encuesta'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Padrino')),
            ],
        ),
        migrations.CreateModel(
            name='Afinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afinidad', models.FloatField()),
                ('mechon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mechon')),
                ('padrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Padrino')),
            ],
        ),
        migrations.AddField(
            model_name='mechon',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Grupo'),
        ),
    ]
