# Generated by Django 2.2 on 2019-06-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190627_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='anno_actual',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
