# Generated by Django 2.2 on 2019-07-01 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='anno_actual',
        ),
        migrations.AddField(
            model_name='grupo',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='afinacion',
            name='afinidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='anno',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mechon',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='padrino',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='generacion',
            field=models.IntegerField(default=2019),
        ),
    ]
