# Generated by Django 2.2 on 2019-07-01 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190630_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='fecha_realizacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
