# Generated by Django 2.2 on 2019-07-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190701_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='emailPersonal',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
