# Generated by Django 2.2 on 2019-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190702_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emailPersonal',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
