# Generated by Django 2.2 on 2019-07-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190702_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
