# Generated by Django 2.2 on 2019-07-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190702_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='activado',
            field=models.BooleanField(default=False),
        ),
    ]
