# Generated by Django 2.2.4 on 2019-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='activado',
            field=models.BooleanField(default=False),
        ),
    ]
