# Generated by Django 2.2 on 2019-08-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_student', models.CharField(choices=[('PR', 'Mechon'), ('AH', 'Ahijado')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pref_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_pref_from', to='matchmaking.Person')),
                ('pref_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_pref_to', to='matchmaking.Person')),
            ],
            options={
                'ordering': ['id', 'pref_order'],
            },
        ),
    ]
