# Generated by Django 2.2.4 on 2019-08-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='pref_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_act_pref_from', to='usuarios.Actividad'),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='pref_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_act_to', to='usuarios.Actividad'),
        ),
    ]
